### PR TITLE
[5026] Use SOLR_JAVA_MEM instead of SOLR_JAVA_OPTS

### PR DESCRIPTION
**Pull request by phuongnq**
### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/5026

### CODE REVIEW

**Review by sumerjabri — APPROVED** [review]

**Review by avasquez614 — CHANGES_REQUESTED** [review]
@phuongnq I don't know if I 100% agree with the change. I understand the need to change to `SOLR_JAVA_MEM` but removing `SOLR_JAVA_OPTS` removes the clients' ability to specify other options that are not memory, like system properties `-Dmy.property=value`. Can we leave `SOLR_JAVA_OPTS` empty and add a comment to the property that it's preferable to start using `SOLR_JAVA_MEM` for memory settings changes?

@sumerjabri @alhambrav @jdrossl @yacdaniel we need to make sure we handle this as part of the upgrade scripts (if possible) and document this very well.

**Comment by phuongnq** [comment]
@sumerjabri I believe we removed Solr parameters in Crafter 4, so there is no change on Crafter 4 for this PR.

**Comment by phuongnq** [comment]
Actually, I separated more to use both `SOLR_JAVA_MEM` and `SOLR_JAVA_STACK_SIZE`. Without `SOLR_JAVA_STACK_SIZE`, there is another duplicated stack size by default `-Xss256k`.

See comment in https://github.com/craftercms/docker-compose/pull/29

**Comment by phuongnq** [comment]
@sumerjabri @avasquez614 Just a note, in the PR, we removed the default `-Xms512m` from the Solr setting by overriding `SOLR_JAVA_MEM` with only `-Xmx` option. Let me know if we should add `-Xms` (with a smaller value or equal to default `-Xmx1G`) to the parameter.

**Review by sumerjabri — APPROVED** [review]

**Pull request merged**
